
import { User } from '../types';

const userTabs: (User['allowedTabs']) = [
    // Features allowed for the 'user' role as per user request
    'dashboard',
    'scoping',
    'planning',
    'catalog',
    'bac-analytics',
    'infographics',
    'flow',
    'checklist',
    'agreements',
    'downloadable-forms',
    'directory',
    'catalog-tutorial',
    'account'
];

export const users: User[] = [
  // Super Admins
  {
    id: 1,
    username: 'admin',
    password: 'admin',
    role: 'admin',
    fullName: 'Administrator Prime',
    department: 'System Administration',
    allowedTabs: 'all',
  },
  {
    id: 2,
    username: 'litogarin@gmail.com',
    password: '@@Password2025',
    role: 'admin',
    fullName: 'Lito Garin',
    department: 'System Administration',
    allowedTabs: 'all',
  },
  // Department Users from the chart
  { id: 101, username: 'cityagri@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: "City Agriculturist's Office User", department: "City Agriculturist's Office", allowedTabs: userTabs },
  { id: 102, username: 'cityassessor@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: "City Assessor's Office User", department: "City Assessor's Office", allowedTabs: userTabs },
  { id: 103, username: 'bha@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'Bacolod Housing Authority User', department: 'Bacolod Housing Authority', allowedTabs: userTabs },
  { id: 104, username: 'bcc@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'Bacolod City College User', department: 'Bacolod City College', allowedTabs: userTabs },
  { id: 105, username: 'citylib@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'Bacolod City Public Library User', department: 'Bacolod City Public Library', allowedTabs: userTabs },
  { id: 106, username: 'bcpo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'Bacolod City Police Office User', department: 'Bacolod City Police Office', allowedTabs: userTabs },
  { id: 107, username: 'bcydo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'Bacolod City Youth Development Office User', department: 'Bacolod City Youth Development Office', allowedTabs: userTabs },
  { id: 108, username: 'benro@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BENRO User', department: 'Bacolod Environment & Natural Resources Office', allowedTabs: userTabs },
  { id: 109, username: 'hmd07012024@gmail.com', password: 'password', role: 'user', fullName: 'HMD User', department: 'General User', allowedTabs: userTabs },
  // Newly added users
  { id: 110, username: 'bfp@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BFP User', department: 'Bureau of Fire Protection', allowedTabs: userTabs },
  { id: 111, username: 'bttmd@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BTTMD User', department: 'BTTMD Office', allowedTabs: userTabs },
  { id: 112, username: 'citybudget@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'City Budget User', department: 'City Budget Office', allowedTabs: userTabs },
  { id: 113, username: 'coop@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'COOP User', department: 'Cooperatives Office', allowedTabs: userTabs },
  { id: 114, username: 'lcr@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'LCR User', department: 'Local Civil Registrar', allowedTabs: userTabs },
  { id: 115, username: 'ceo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CEO User', department: "City Engineer's Office", allowedTabs: userTabs },
  { id: 116, username: 'cho@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CHO User', department: 'City Health Office', allowedTabs: userTabs },
  { id: 117, username: 'clo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CLO User', department: 'City Legal Office', allowedTabs: userTabs },
  { id: 118, username: 'cityadmin@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'City Admin User', department: "City Administrator's Office", allowedTabs: userTabs },
  { id: 119, username: 'bac@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BAC User', department: 'Bids and Awards Committee', allowedTabs: userTabs },
  { id: 120, username: 'bplo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BPLO User', department: 'Business Permits and Licensing Office', allowedTabs: userTabs },
  { id: 121, username: 'pio@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'PIO User', department: 'Public Information Office', allowedTabs: userTabs },
  { id: 122, username: 'coa@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'COA User', department: 'Commission on Audit', allowedTabs: userTabs },
  { id: 123, username: 'cpdo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CPDO User', department: 'City Planning and Development Office', allowedTabs: userTabs },
  { id: 124, username: 'accountant@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'Accountant User', department: "City Accountant's Office", allowedTabs: userTabs },
  { id: 125, username: 'cto_landtax@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CTO Landtax User', department: "City Treasurer's Office - Land Tax", allowedTabs: userTabs },
  { id: 126, username: 'cto_license@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CTO License User', department: "City Treasurer's Office - License", allowedTabs: userTabs },
  { id: 127, username: 'cityvet@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'City Vet User', department: 'City Veterinary Office', allowedTabs: userTabs },
  { id: 128, username: 'dilg@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DILG User', department: 'DILG Office', allowedTabs: userTabs },
  { id: 129, username: 'drrmo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DRRMO User', department: 'DRRMO', allowedTabs: userTabs },
  { id: 130, username: 'dssd@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DSSD User', department: 'DSSD', allowedTabs: userTabs },
  { id: 131, username: 'gso@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'GSO User', department: 'General Services Office', allowedTabs: userTabs },
  { id: 132, username: 'hrms@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'HRMS User', department: 'Human Resource Management Services', allowedTabs: userTabs },
  { id: 133, username: 'BCDledipoffice@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BCD LEDIP Office User', department: 'BCD LEDIP Office', allowedTabs: userTabs },
  { id: 134, username: 'mitcs@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'MITCS User', department: 'MITCS', allowedTabs: userTabs },
  { id: 135, username: 'obo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'OBO User', department: 'Office of the Building Official', allowedTabs: userTabs },
  { id: 136, username: 'popcom@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'POPCOM User', department: 'POPCOM Office', allowedTabs: userTabs },
  { id: 137, username: 'sp@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'SP User', department: 'Sangguniang Panlungsod', allowedTabs: userTabs },
  { id: 138, username: 'tourism@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'Tourism User', department: 'Tourism Office', allowedTabs: userTabs },
  { id: 139, username: 'ias@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'IAS User', department: 'Internal Audit Service', allowedTabs: userTabs },
  { id: 140, username: 'maso@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'MASO User', department: 'MASO', allowedTabs: userTabs },
  { id: 141, username: 'mtcc@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'MTCC User', department: 'MTCC', allowedTabs: userTabs },
  { id: 142, username: 'jalandra.che@gmail.com', password: 'password', role: 'user', fullName: 'Jalandra Che User', department: 'General User', allowedTabs: userTabs },
  { id: 143, username: 'benro.bacolod25@gmail.com', password: 'password', role: 'user', fullName: 'Benro Bacolod25 User', department: 'General User', allowedTabs: userTabs },
  { id: 144, username: 'dps@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DPS User', department: 'Department of Public Services', allowedTabs: userTabs },
  { id: 145, username: 'medecielodaniel26@yahoo.com', password: 'password', role: 'user', fullName: 'Medecielodaniel26 User', department: 'General User', allowedTabs: userTabs },
  { id: 146, username: 'pesobcd@gmail.com', password: 'password', role: 'user', fullName: 'Pesobcd User', department: 'General User', allowedTabs: userTabs },
  { id: 147, username: 'edjomar888@gmail.com', password: 'password', role: 'user', fullName: 'Edjomar888 User', department: 'General User', allowedTabs: userTabs },
  { id: 148, username: 'bacolodcityassessors@gmail.com', password: 'password', role: 'user', fullName: 'Bacolodcityassessors User', department: 'General User', allowedTabs: userTabs },
  { id: 149, username: 'posoofficial710@gmail.com', password: 'password', role: 'user', fullName: 'Posoofficial710 User', department: 'General User', allowedTabs: userTabs },
  { id: 150, username: 'ruthsylesy@gmail.com', password: 'password', role: 'user', fullName: 'Ruthsylesy User', department: 'General User', allowedTabs: userTabs },
  { id: 151, username: 'lcrbacolod@gmail.com', password: 'password', role: 'user', fullName: 'Lcrbacolod User', department: 'General User', allowedTabs: userTabs },
  { id: 152, username: 'bacolodsportsoffice@gmail.com', password: 'password', role: 'user', fullName: 'Bacolodsportsoffice User', department: 'General User', allowedTabs: userTabs },
  { id: 153, username: 'nir.metrobacoloddjmd@bjmp.gov.ph', password: 'password', role: 'user', fullName: 'JSUPT NORBERTO G MICIANO JR', department: 'BJMP Office', allowedTabs: userTabs },
  { id: 154, username: 'demo', password: 'password', role: 'user', fullName: 'Demo User', department: 'Demo Department', allowedTabs: userTabs },
  { id: 155, username: 'pdao.bacolod@yahoo.com', password: 'password', role: 'user', fullName: 'Pdao Bacolod User', department: 'General User', allowedTabs: userTabs },
  { id: 156, username: 'mflorentino@yahoo.com', password: 'password', role: 'user', fullName: 'Mflorentino User', department: 'General User', allowedTabs: userTabs },
  { id: 157, username: 'bacolodpdao@gmail.com', password: 'password', role: 'user', fullName: 'Bacolodpdao User', department: 'General User', allowedTabs: userTabs },
  { id: 158, username: 'jupitermiranda3@gmail.com', password: 'password', role: 'user', fullName: 'Jupitermiranda3 User', department: 'General User', allowedTabs: userTabs },
  { id: 159, username: 'cpdobacolod@gmail.com', password: 'password', role: 'user', fullName: 'Cpdobacolod User', department: 'General User', allowedTabs: userTabs },
  { id: 160, username: 'ann.sumagaysay71@gmail.com', password: 'password', role: 'user', fullName: 'Ann Sumagaysay71 User', department: 'General User', allowedTabs: userTabs },
  { id: 161, username: 'earlrarejob@gmail.com', password: 'password', role: 'user', fullName: 'Earlrarejob User', department: 'General User', allowedTabs: userTabs },
  { id: 162, username: 'rtcbacolod.occ@gmail.com', password: 'password', role: 'user', fullName: 'Rtcbacolod Occ User', department: 'General User', allowedTabs: userTabs },
  { id: 163, username: 'deputycitydirector@gmail.com', password: 'password', role: 'user', fullName: 'Deputycitydirector User', department: 'General User', allowedTabs: userTabs },
  { id: 164, username: 'maglasang.pinky@yahoo.com', password: 'password', role: 'user', fullName: 'Maglasang Pinky User', department: 'General User', allowedTabs: userTabs },
  { id: 165, username: 'euniceciocondrrmo@gmail.com', password: 'password', role: 'user', fullName: 'Euniceciocondrrmo User', department: 'General User', allowedTabs: userTabs },
  { id: 166, username: 'trenzdivinagracia@gmail.com', password: 'password', role: 'user', fullName: 'Trenzdivinagracia User', department: 'General User', allowedTabs: userTabs },
  { id: 167, username: 'mikeejakelozada@gmail.com', password: 'password', role: 'user', fullName: 'Mikeejakelozada User', department: 'General User', allowedTabs: userTabs },
  { id: 168, username: 'lila.arro@deped.gov.ph', password: 'password', role: 'user', fullName: 'Lila Arro User', department: 'DepEd Office', allowedTabs: userTabs },
  { id: 169, username: 'carcardable1974@gmail.com', password: 'password', role: 'user', fullName: 'Carcardable1974 User', department: 'General User', allowedTabs: userTabs },
  { id: 170, username: 'derderjohnrey@gmail.com', password: 'password', role: 'user', fullName: 'Derderjohnrey User', department: 'General User', allowedTabs: userTabs },
  { id: 171, username: 'dyanntorrecarion82@gmail.com', password: 'password', role: 'user', fullName: 'Dyanntorrecarion82 User', department: 'General User', allowedTabs: userTabs },
  { id: 172, username: 'princessdizon6@gmail.com', password: 'password', role: 'user', fullName: 'Princessdizon6 User', department: 'General User', allowedTabs: userTabs },
  { id: 173, username: 'cbobacolod@gmail.com', password: 'password', role: 'user', fullName: 'City Budget Office Gmail User', department: 'City Budget Office', allowedTabs: userTabs },
  { id: 174, username: 'ocpbacolod@doj.gov.ph', password: 'password', role: 'user', fullName: "City Prosecutor's Office User", department: "City Prosecutor's Office", allowedTabs: userTabs },
  {
    id: 175,
    username: 'acitymayorsoffice@gmail.com',
    password: 'password',
    role: 'user',
    fullName: "City Mayor's Office User",
    department: "City Mayor's Office",
    allowedTabs: userTabs
  },
  {
    id: 176,
    username: 'bbh@bacolodcity.gov.ph',
    password: 'password',
    role: 'user',
    fullName: "Bacolod Boy's Home User",
    department: "Bacolod Boy's Home",
    allowedTabs: userTabs
  },
  {
    id: 177,
    username: 'benro.bacolod25@gmail.com',
    password: 'password',
    role: 'user',
    fullName: 'Benro Bacolod25 User',
    department: 'General User',
    allowedTabs: userTabs,
  },
  {
    id: 178,
    username: 'kabonales@bacolodcity.gov.ph',
    password: 'password',
    role: 'user',
    fullName: 'K Abonales User',
    department: 'General User',
    allowedTabs: userTabs,
  },
  {
    id: 179,
    username: 'maryjo.rosal@gmail.com',
    password: 'password',
    role: 'user',
    fullName: 'Mary Jo Rosal',
    department: 'General User',
    allowedTabs: userTabs,
  },
];
