
import { User } from '../types';

const userTabs: (User['allowedTabs']) = [
    // Features allowed for the 'user' role as per user request
    'dashboard',
    'planning',
    'catalog',
    'bac-analytics',
    'flow',
    'checklist',
    'agreements',
    'downloadable-forms',
    'account'
];

export const users: User[] = [
  // Super Admins
  {
    id: 1,
    username: 'admin',
    password: 'admin',
    role: 'admin',
    fullName: 'Administrator Prime',
    department: 'System Administration',
    allowedTabs: 'all',
  },
  {
    id: 2,
    username: 'litogarin@gmail.com',
    password: '@@Password2025',
    role: 'admin',
    fullName: 'Lito Garin',
    department: 'System Administration',
    allowedTabs: 'all',
  },
  // Department Users from the chart
  { id: 101, username: 'agri@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'AGRI User', department: 'AGRI', allowedTabs: userTabs },
  { id: 102, username: 'assr@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'ASSR User', department: 'ASSR', allowedTabs: userTabs },
  { id: 103, username: 'bacchp@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BACCHP User', department: 'BACCHP', allowedTabs: userTabs },
  { id: 104, username: 'bcc@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BCC User', department: 'BCC', allowedTabs: userTabs },
  { id: 105, username: 'bcpl@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BCPL User', department: 'BCPL', allowedTabs: userTabs },
  { id: 106, username: 'bcpo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BCPO User', department: 'BCPO', allowedTabs: userTabs },
  { id: 107, username: 'bcydo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BCYDO User', department: 'BCYDO', allowedTabs: userTabs },
  { id: 108, username: 'benro@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BENRO User', department: 'BENRO', allowedTabs: userTabs },
  { id: 109, username: 'bfp@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BFP User', department: 'BFP', allowedTabs: userTabs },
  { id: 110, username: 'bha@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BHA User', department: 'BHA', allowedTabs: userTabs },
  { id: 111, username: 'bttmd@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BTTMD User', department: 'BTTMD', allowedTabs: userTabs },
  { id: 112, username: 'cbo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CBO User', department: 'CBO', allowedTabs: userTabs },
  { id: 113, username: 'ccldo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CCLDO User', department: 'CCLDO', allowedTabs: userTabs },
  { id: 114, username: 'ccr@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CCR User', department: 'CCR', allowedTabs: userTabs },
  { id: 115, username: 'cda@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CDA User', department: 'CDA', allowedTabs: userTabs },
  { id: 116, username: 'ceohighway@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CEO-Highway Maintenance User', department: 'CEO-Highway Maintenance', allowedTabs: userTabs },
  { id: 117, username: 'ceomotorpool@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CEO-Motorpool Division User', department: 'CEO-Motorpool Division', allowedTabs: userTabs },
  { id: 118, username: 'ceoadmin@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CEO-Administrative Division User', department: 'CEO-Administrative Division', allowedTabs: userTabs },
  { id: 119, username: 'ceoelectrical@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CEO-Electrical Division User', department: 'CEO-Electrical Division', allowedTabs: userTabs },
  { id: 120, username: 'ceoengineering@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CEO-Engineering Division User', department: 'CEO-Engineering Division', allowedTabs: userTabs },
  { id: 121, username: 'ceoplanning@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CEO-Planning & Design Division User', department: 'CEO-Planning & Design Division', allowedTabs: userTabs },
  { id: 122, username: 'ceopublicworks@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CEO-Public Works Division User', department: 'CEO-Public Works Division', allowedTabs: userTabs },
  { id: 123, username: 'ceospecial@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CEO-Special Services Division User', department: 'CEO-Special Services Division', allowedTabs: userTabs },
  { id: 124, username: 'cho@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CHO User', department: 'CHO', allowedTabs: userTabs },
  { id: 125, username: 'chomental@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CHO MENTAL User', department: 'CHO MENTAL', allowedTabs: userTabs },
  { id: 126, username: 'choli@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CHO-LI User', department: 'CHO-LI', allowedTabs: userTabs },
  { id: 127, username: 'clo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CLO User', department: 'CLO', allowedTabs: userTabs },
  { id: 128, username: 'cmo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CMO User', department: 'CMO', allowedTabs: userTabs },
  { id: 129, username: 'bac@bacolodcity.gov.ph', password: 'bacbacolod2025', role: 'admin', fullName: 'BAC Admin User', department: 'Bids and Awards Committee', allowedTabs: 'all' },
  { id: 130, username: 'cmobacchp@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CMO-BacCHP User', department: 'CMO-BacCHP', allowedTabs: userTabs },
  { id: 131, username: 'cmobplo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CMO-BPLO User', department: 'CMO-BPLO', allowedTabs: userTabs },
  { id: 132, username: 'cmooba@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CMO-OBA User', department: 'CMO-OBA', allowedTabs: userTabs },
  { id: 133, username: 'cmopeso@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CMO-PESO User', department: 'CMO-PESO', allowedTabs: userTabs },
  { id: 134, username: 'cmopio@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CMO-PIO User', department: 'CMO-PIO', allowedTabs: userTabs },
  { id: 135, username: 'cmoposo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CMO-POSO User', department: 'CMO-POSO', allowedTabs: userTabs },
  { id: 136, username: 'cmosectoral@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CMO-SECTORAL User', department: 'CMO-SECTORAL', allowedTabs: userTabs },
  { id: 137, username: 'cmosupply@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CMO-SUPPLY User', department: 'CMO-SUPPLY', allowedTabs: userTabs },
  { id: 138, username: 'coa@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'COA User', department: 'COA', allowedTabs: userTabs },
  { id: 139, username: 'comelec@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'COMELEC User', department: 'COMELEC', allowedTabs: userTabs },
  { id: 140, username: 'cpdo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CPDO User', department: 'CPDO', allowedTabs: userTabs },
  { id: 141, username: 'cpohoj@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CPOHOJ User', department: 'CPOHOJ', allowedTabs: userTabs },
  { id: 142, username: 'ctad@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CTAD User', department: 'CTAD', allowedTabs: userTabs },
  { id: 143, username: 'ctdo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CTDO User', department: 'CTDO', allowedTabs: userTabs },
  { id: 144, username: 'ctoadmin@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CTO-ADMIN User', department: 'CTO-ADMIN', allowedTabs: userTabs },
  { id: 145, username: 'ctocash@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CTO-CASH User', department: 'CTO-CASH', allowedTabs: userTabs },
  { id: 146, username: 'ctolandtax@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CTO-LANDTAX User', department: 'CTO-LANDTAX', allowedTabs: userTabs },
  { id: 147, username: 'ctolicense@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CTO-LICENSE User', department: 'CTO-LICENSE', allowedTabs: userTabs },
  { id: 148, username: 'cvo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CVO User', department: 'CVO', allowedTabs: userTabs },
  { id: 149, username: 'dilg@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DILG User', department: 'DILG', allowedTabs: userTabs },
  { id: 150, username: 'drrmf@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DRRMF User', department: 'DRRMF', allowedTabs: userTabs },
  { id: 151, username: 'drrmo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DRRMO User', department: 'DRRMO', allowedTabs: userTabs },
  { id: 152, username: 'dssd@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DSSD User', department: 'DSSD', allowedTabs: userTabs },
  { id: 153, username: 'dssdantipoverty@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DSSD-ANTI POVERTY User', department: 'DSSD-ANTI POVERTY', allowedTabs: userTabs },
  { id: 154, username: 'dssdcadac@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DSSD-CADAC User', department: 'DSSD-CADAC', allowedTabs: userTabs },
  { id: 155, username: 'dssdgad@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DSSD-GAD User', department: 'DSSD-GAD', allowedTabs: userTabs },
  { id: 156, username: 'dssdlcpc@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DSSD-LCPC User', department: 'DSSD-LCPC', allowedTabs: userTabs },
  { id: 157, username: 'dssdosca@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DSSD-OSCA User', department: 'DSSD-OSCA', allowedTabs: userTabs },
  { id: 158, username: 'dssdpwd@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DSSD-PWD User', department: 'DSSD-PWD', allowedTabs: userTabs },
  { id: 159, username: 'dssdsdc@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DSSD-SDC User', department: 'DSSD-SDC', allowedTabs: userTabs },
  { id: 160, username: 'gso@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'GSO User', department: 'GSO', allowedTabs: userTabs },
  { id: 161, username: 'hrms@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'HRMS User', department: 'HRMS', allowedTabs: userTabs },
  { id: 162, username: 'ledipo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'LEDIPO User', department: 'LEDIPO', allowedTabs: userTabs },
  { id: 163, username: 'mitcs@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'MITCS User', department: 'MITCS', allowedTabs: userTabs },
  { id: 164, username: 'obo@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'OBO User', department: 'OBO', allowedTabs: userTabs },
  { id: 165, username: 'oca@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'OCA User', department: 'OCA', allowedTabs: userTabs },
  { id: 166, username: 'ocamaso@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'OCA-MASO User', department: 'OCA-MASO', allowedTabs: userTabs },
  { id: 167, username: 'popcom@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'POPCOM User', department: 'POPCOM', allowedTabs: userTabs },
  { id: 168, username: 'sectoral@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'SECTORAL User', department: 'SECTORAL', allowedTabs: userTabs },
  { id: 169, username: 'seeu@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'SEEU User', department: 'SEEU', allowedTabs: userTabs },
  { id: 170, username: 'sp@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'SP User', department: 'SP', allowedTabs: userTabs },
  { id: 171, username: 'tourism@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'TOURISM User', department: 'TOURISM', allowedTabs: userTabs },
  { id: 172, username: 'ubsd@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'UBSD User', department: 'UBSD', allowedTabs: userTabs },
  { id: 173, username: 'various@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'Various Department User', department: 'Various Department', allowedTabs: userTabs },
  { id: 174, username: 'dssdhomeforblind@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'DSSD-Home for the Blind User', department: 'DSSD-Home for the Blind', allowedTabs: userTabs },
  { id: 175, username: 'paad@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'PAAD User', department: 'PAAD', allowedTabs: userTabs },
  { id: 176, username: 'seeumarkets@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'SEEU-Markets User', department: 'SEEU-Markets', allowedTabs: userTabs },
  { id: 177, username: 'cmoprinting@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'CMO-Printing User', department: 'CMO-Printing', allowedTabs: userTabs },
  { id: 178, username: 'bbh@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'BBH User', department: 'BBH', allowedTabs: userTabs },
  { id: 179, username: 'ias@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'IAS User', department: 'IAS', allowedTabs: userTabs },
  { id: 180, username: 'jjwc@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'JJWC User', department: 'JJWC', allowedTabs: userTabs },
  { id: 181, username: 'maso@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'MASO User', department: 'MASO', allowedTabs: userTabs },
  { id: 182, username: 'mtcc@bacolodcity.gov.ph', password: 'password', role: 'user', fullName: 'MTCC User', department: 'MTCC', allowedTabs: userTabs },
  { id: 183, username: 'jalandra.che@gmail.com', password: 'password', role: 'user', fullName: 'Che Jalandra', department: 'CHO', allowedTabs: userTabs },
  { id: 184, username: 'benro.bacolod25@gmail.com', password: 'password', role: 'user', fullName: 'BENRO Bacolod', department: 'BENRO', allowedTabs: userTabs },
];
